### ISSUE TITLE
Produce a warning if two images' dimensions don't match

### ISSUE THREAD

**Issue by nathanmarks** [mapbox/pixelmatch#23]
I'm having difficulty getting a usable diff image from this lib, I've provided output from `blink-diff` as a comparison for the same images.

Baseline:

![chrome-50 0 2661 86-linux](https://cloud.githubusercontent.com/assets/4420103/17486718/dc35e338-5d5f-11e6-8e27-01449555397c.png)

Comparison:

![chrome-50 0 2661 86-linux](https://cloud.githubusercontent.com/assets/4420103/17486732/e7ac308c-5d5f-11e6-840d-fb5a69354191.png)

**pixelmatch** diff image:

![chrome-50 0 2661 86-linux-diff](https://cloud.githubusercontent.com/assets/4420103/17486747/f8e225d2-5d5f-11e6-9485-2e5d3171f36d.png)

**blink-diff** diff image:

![chrome-50 0 2661 86-linux-diff](https://cloud.githubusercontent.com/assets/4420103/17487210/db6c0d22-5d61-11e6-9e33-1c0a01e95d58.png)

**Comment by mourner** [comment]
This is because the two images are quite different (switch between the two images — all the letters shift positions in various degrees). Blink-diff's algorithm is very naive and will ignore any differences if it can find the original pixel somewhere in the vicinity, but this can lead to many false negatives (undetected mismatches) that this library avoids. So it's more of a design decision — it does a pixel-perfect comparison.

**Comment by nathanmarks** [comment]
@mourner 

1. Is the same true for the `resemblejs` algorithm?

2. The purpose of my usage is to diff front end components screenshotted via selenium. Do you think it's possible to achieve what I'm looking for in terms of diff clarity with `pixelmatch`? I'm wondering if the `blink-diff` algorithm, while naive, suits my needs better due to the nature of the tests as seen above.

**Comment by mourner** [comment]
To make the diff clearer, try increasing the threshold for pixelmatch. I believe resemble-js isn't very sensitive to differences as well. It can be good enough if you want to detect really noticeable differences like a huge object absent on one of the images, but the goal of this library was to create a very sensitive library suitable for testing a graphics-heavy map rendering engine across platforms.

**Comment by mourner** [comment]
@nathanmarks ah damn, now I see what's going on. The two images you compare have different dimensions — the first is 156px width and the second 154px. This breaks the comparison completely because the pixel positions are shifted. I think I need to add a warning to the command line tool if the dimensions of two images don't match.

**Comment by nathanmarks** [comment]
@mourner 

Is it possible to anchor the smaller image? This is the two images in photoshop with layer mode difference and 58% opacity:

![image](https://t.gyazo.com/teams/nathanmarks/55b4e37b222b7681221542629fed347f.png)

**Comment by mourner** [comment]
@nathanmarks possible, but I'd like to keep the tool simple. I think it's fair to require equal dimensions, and if someone wants a workaround, you can always slice the image data in a way you need.
